### ISSUE TITLE
Does not work for absolutely positioned elements

### ISSUE THREAD

**Issue by buschtoens** [wnr/element-resize-detector#80]
Apparently absolutely positioned elements are incompatible.

https://jsbin.com/veyulajohu/3/edit?html,css,js,output

```css
#watched {
  box-sizing: border-box;
  position: absolute;
  top: 10%;
  left: 10%;
  
  height: 80%;
  width: 80%;
  padding: 3em;
  
  background: red;
}
```

```js
var erd = elementResizeDetectorMaker({
  strategy: "scroll" 
});

var el = document.getElementById("watched");

erd.listenTo(el, function(element) {
  var width = element.offsetWidth;
  var height = element.offsetHeight;
  el.innerText = width + " x " + height;
});
```
